dist: trusty

cache:
  pip: true

matrix:
  fast_finish: true
  include:
  - os: linux
    python: 2.7
  - os: linux
    python: 3.5


install:
- pip install -U pip  # the pip version on travis is too old
- pip install tensorflow-gpu


before_install:
  - python -c "import tensorflow as tf; print('TensorFlow '+ tf.__version__)"


script:
  - cd matrix_add && flake8 .
  - cd matrix_add && make


notifications:
  email: false