dist: trusty

cache:
  pip: true


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - nvidia-cuda-dev
      - nvidia-profiler
      - nvidia-cuda-toolkit
      - g++
      - g++-4.9
      - g++-5

matrix:
  fast_finish: true
  include:
  - os: linux
    python: 2.7
  - os: linux
    python: 3.5


install:
- pip install -U pip  # the pip version on travis is too old
- pip install tensorflow-gpu flake8

script:
  - python -c "import tensorflow as tf; print('TensorFlow '+ tf.__version__)"
  - cd matrix_add && flake8 .
  - pwd
  - ls -la
  - cd matrix_add && make


notifications:
  email: false